# 1. My Lane (or Freestyle) and Why

## My Lane

I selected **Lane 2 – Refresh / Content Opportunity Scoring**.

I chose this lane because it focuses on helping content teams prioritize which pages should be reviewed first using observable search and engagement signals. Instead of automating SEO decisions, this lane supports human decision-making by ranking pages according to measurable evidence.

This aligns with my interest in machine learning and explainable decision-support systems, where models assist people in making better decisions rather than replacing them.

# 2. The Question

## Decision

Which content pages should be reviewed first for refresh based on search and engagement signals?

## Unit of Analysis

One content page.

## Output

A ranked list of content pages with refresh scores, confidence levels, and reason codes.

## Action

A content manager reviews the highest-ranked pages and decides whether to refresh, expand, protect, merge, prune, or monitor each page.

## Cost of a Wrong Recommendation

If an important page is missed, valuable search traffic may continue to decline.

If an unnecessary page is recommended, time and effort may be wasted on content with little improvement potential.

## Why Machine Learning Helps

Machine learning can learn patterns across multiple search and engagement signals simultaneously, helping prioritize pages more effectively than simple fixed rules while keeping the final decision with human reviewers.

# 3. Quick Look at the Data

The following code explores the starter dataset and calculates a few summary statistics to better understand the available search and engagement signals.

In [3]:
import pandas as pd

df = pd.read_csv("../../data/raw/content_refresh_anonymized.csv")

print(f"Total content pages: {len(df):,}")
print("\nTrend Direction:")
print(df["trend_direction"].value_counts())

print(f"\nAverage 90-day impressions: {df['impressions_90d'].mean():.2f}")
print(f"Average 90-day sessions: {df['sessions_90d'].mean():.2f}")
print(f"Average CTR: {df['ctr'].mean():.2f}")

Total content pages: 30,000

Trend Direction:
trend_direction
down      16262
stable     5962
up         4388
new        2236
flat       1152
Name: count, dtype: int64

Average 90-day impressions: 5200.37
Average 90-day sessions: 37.07
Average CTR: 0.51


## Observations

I explored the starter dataset to understand its size and the available search signals before defining my approach.

Some key observations are:

- The dataset contains **30,000 content pages**.
- The most common trend is **"down"**, affecting **16,262 pages**.
- The average number of **90-day impressions** is **5,200.37**.
- The average number of **90-day sessions** is **37.07**.
- The average **CTR** is **0.51**.

These observations indicate that the dataset contains enough search and engagement information to support a content opportunity scoring approach.

# 4. Careful Words

This project is intended to prioritize content pages for human review rather than automatically deciding which pages should be refreshed.

The ranking is based on observable search and engagement signals and should not be interpreted as proof that refreshing a page will improve its performance.

Machine learning provides evidence-based recommendations, while the final decision should remain with human reviewers.

# 5. Self Check

- ✅ I selected one predefined lane.
- ✅ I clearly defined the decision.
- ✅ I identified the unit of analysis.
- ✅ I described the expected output.
- ✅ I explained the action someone could take.
- ✅ I discussed the cost of a wrong recommendation.
- ✅ I used real numbers from the starter dataset.
- ✅ I explained why machine learning is appropriate.
- ✅ I used careful language and avoided unsupported claims.